name: Node Code Coverage

on:
  push:
    branches:
      - master
    paths:
      - "javascript/**"

jobs:
  codacy-coverage:
    name: Run and Push Node Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Run Node Coverage
        run: npm run coverage