name: Node Code Coverage

on:
  push:
    branches:
      - master
    paths:
      - "javascript/**"

jobs:
  codacy-coverage:
    defaults:
      run:
        working-directory: javascript
      
    name: Run and Push Node Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
        
      - name: Npm Install
        run: npm install

      - name: Run Node Coverage
        run: npm run coverage

      - name: Download other coverage reports
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: python.yaml
          name: coverage-report
          check_artifacts:  true
      
      - name: Upload Node Coverage
        env:
          CODACY_PROJECT_TOKEN: a95e7f2eaf7742eab01dbd7b526283c8
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info

      - name: Upload Python Coverage
        env:
          CODACY_PROJECT_TOKEN: a95e7f2eaf7742eab01dbd7b526283c8
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ../coverage.xml
      
      - name: Archive code coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: javascript/coverage/lcov.info
      
          
